### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by lishid** [jplattel/obsidian-query-language#10]
https://github.com/jplattel/obsidian-query-language/blob/e2d9ca5d4e1d4f640c4517a2360e59c222d8cdd1/src/main.ts#L88
Please don't use `cachedData`. This is an internal API that is sometimes null or undefined.

**Comment by jplattel** [comment]
Yes, I'm migrating to getAllMarkdownFiles in the next version, will update this issue when I'm done working on it :)

**Comment by jplattel** [comment]
Hey @lishid , I've removed the cachedData reference in the latest commits! 

Just one more thing, I'm currently using `ctx.sourcePath` at `https://github.com/jplattel/obsidian-query-language/blob/main/src/renderer.ts#L57` to determine the current file the renderer is processing. Since this attribute is not public, is there any other way to determine the path of the current note?

**Comment by lishid** [comment]
You can keep that there, we'll probably expose it one day since I can't think of anything better.

**Comment by jplattel** [comment]
Thanks! Closing this issues as it's solved in 2.0.0! :)
