### ISSUE TITLE
[Bug] Cannot query the oldest notes by using "-created"

### ISSUE THREAD

**Issue by Quorafind** [jplattel/obsidian-query-language#2]
When I used `sort: "-created"` in code-block, it didn't show results correctly when renderred it.
like: I used
```oql
name: 
debug: true
query: law
template: "table"
sort: '-created'
limit: 5
badge: false
fields: ['title', 'created']
```
to output five oldest files. However, the 7th file's created time and modified time were both earlier than the 5th file's.
![image](https://user-images.githubusercontent.com/13215013/106086048-540dad00-615c-11eb-9ec7-b532bc597b58.png)

**Comment by jplattel** [comment]
Thanks for the bug-report @Quorafind! The screenshots help out a lot! I was expecting the .sort() functions of JS to be kind of stable, but sadly it isn't.... That's why you found this bug, I'm looking into using sortBy of lodash instead: https://lodash.com/docs/#sortBy 

This will be solved in the next release :)

**Comment by Quorafind** [comment]
Quick fix! Thanks for quick react, wish you a good day!
