### ISSUE TITLE
Interesting Bug?

### ISSUE THREAD

**Issue by Quorafind** [jplattel/obsidian-query-language#3]
The plugin works really well! But there is new interesting bug? When I use :
```oql
name: 
query: "'blabla"
template: "table"
sort: '-modified'
debug: true
badge: false
fields: ['title', 'modified', 'created']
```
to query all my files that contain blabla, modified time of some files are earlier than their created time 😂 . like：
![image](https://user-images.githubusercontent.com/13215013/106159895-3bcf7980-61c0-11eb-8cff-026c115773f6.png)
You can catch the bug on the first four files in this pic.

**Comment by jplattel** [comment]
I'm not sure this is a bug in this plugin, it just might by Obsidian itself that's somehow providing the wrong dates..

I'm using the ctime & mtime of the File interface from Obsidian itself: https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L698 only using the Date() to convert it to an ISO timestamp instead of a unix epoch time.

**Comment by Quorafind** [comment]
Oh, so I need to add a bug report on the Obsidian forum later. Thanks again!

**Comment by jplattel** [comment]
Yup, I think that's the best thing to do, closing this for now :)
