### ISSUE TITLE
Feature request - omit current note

### ISSUE THREAD

**Issue by NeighNeighNeigh** [jplattel/obsidian-query-language#5]
Could we prevent the query from including the current note from its results?

**Comment by jplattel** [comment]
Should the note that is containing the query always be omitted? Or omit it by default, only including it when a certain parameter in the query block is set? What would be your preferred solution @NeighNeighNeigh? :)

**Comment by NeighNeighNeigh** [comment]
I doubt I would ever want to include the host note in my results, but there probably should be a way to include it for edge cases. Perhaps it makes most sense to just omit it as part of the query (which I realise now might already be possible?). With Obsidian's search syntax we can filter out files like so `-file:"all about dinosaurs"` … maybe that's all we need here?

**Comment by jplattel** [comment]
That makes sense! I'll omit the note containing the query by default, allowing you to include it by using a parameter like:

```yaml
includeCurrentNote: true
```

As for the query syntax, the plugin uses a different syntax than Obsidian itself, this is due to the fact that the plugin uses a different library for searching. Obsidian doesn't currently expose the search functionality for the API itself. I know this is confusing at times, I hope to improve this in the future :)

**Comment by jplattel** [comment]
In version 1.5.0 I've included the `includeCurrentNote` boolean setting which allows to include the current note. It's now omitted by default. Closing this issue :)
